title: Dan's Mind Space
name: A Place to showcase my Projects and Musings.
user_description: dansmind.space
notes_url: "https://dansmind.space"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.ico
copyright_name: Daniel Dahl
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dansmind.space" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8
google_analytics: UA-175177942-1

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-toc

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: null
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge


sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title
      reverse: true
      order:
        - Welcome.md

toc:
  max_level: 3

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
